/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    'product-categories': ProductCategory;
    service: Service;
    'blog-news-categories': BlogNewsCategory;
    'blog-and-news': BlogAndNew;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    service: ServiceSelect<false> | ServiceSelect<true>;
    'blog-news-categories': BlogNewsCategoriesSelect<false> | BlogNewsCategoriesSelect<true>;
    'blog-and-news': BlogAndNewsSelect<false> | BlogAndNewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    homePage: HomePage;
    footer: Footer;
    contact: Contact;
    aboutus: Aboutus;
    ourproduct: Ourproduct;
    'golf-center': GolfCenter;
    'blog-our-news': BlogOurNew;
    seo: Seo;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    aboutus: AboutusSelect<false> | AboutusSelect<true>;
    ourproduct: OurproductSelect<false> | OurproductSelect<true>;
    'golf-center': GolfCenterSelect<false> | GolfCenterSelect<true>;
    'blog-our-news': BlogOurNewsSelect<false> | BlogOurNewsSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blobUrls?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  skuCode: string;
  imageList?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Select product categories
   */
  categories: (number | ProductCategory)[];
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  features?:
    | {
        /**
         * Upload an SVG or PNG icon for this feature
         */
        icon: number | Media;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * ใส่ keywords สำหรับ SEO (คั่นด้วยเครื่องหมายจุลภาค เช่น keyword1, keyword2)
     */
    keywords?: string | null;
  };
  isActive?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  slug: string;
  /**
   * Brief description of this category
   */
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Order to display categories (lower numbers first)
   */
  displayOrder?: number | null;
  isActive?: boolean | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * ใส่ keywords สำหรับ SEO (คั่นด้วยเครื่องหมายจุลภาค เช่น keyword1, keyword2)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service".
 */
export interface Service {
  id: number;
  slug: string;
  isActive?: boolean | null;
  name: string;
  service?: {
    headertitle?: string | null;
    headerdetail?: string | null;
    headerimage?: (number | null) | Media;
  };
  experiencelist?:
    | {
        titleexperience: string;
        yearexperience: string;
        id?: string | null;
      }[]
    | null;
  content?: {
    icontitle?: (number | null) | Media;
    titleicon?: string | null;
    contentlist?:
      | {
          titlecontent?: string | null;
          detailcontent?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  servicecategorylist?:
    | {
        title?: string | null;
        detail?: string | null;
        imagelist?:
          | {
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footer?: {
    title?: string | null;
    detail?: string | null;
    image?: (number | null) | Media;
    button?: {
      title?: string | null;
      link?: string | null;
    };
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * ใส่ keywords สำหรับ SEO (คั่นด้วยเครื่องหมายจุลภาค เช่น keyword1, keyword2)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-news-categories".
 */
export interface BlogNewsCategory {
  id: number;
  name: string;
  slug: string;
  isActive?: boolean | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * ใส่ keywords สำหรับ SEO (คั่นด้วยเครื่องหมายจุลภาค เช่น keyword1, keyword2)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-and-news".
 */
export interface BlogAndNew {
  id: number;
  name: string;
  slug: string;
  publishedAt?: string | null;
  isActive?: boolean | null;
  /**
   * Select a category
   */
  category?: (number | BlogNewsCategory)[] | null;
  imagelist?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * ใส่ keywords สำหรับ SEO (คั่นด้วยเครื่องหมายจุลภาค เช่น keyword1, keyword2)
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'service';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'blog-news-categories';
        value: number | BlogNewsCategory;
      } | null)
    | ({
        relationTo: 'blog-and-news';
        value: number | BlogAndNew;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  blobUrls?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  skuCode?: T;
  imageList?:
    | T
    | {
        image?: T;
        id?: T;
      };
  categories?: T;
  description?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  isActive?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  displayOrder?: T;
  isActive?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service_select".
 */
export interface ServiceSelect<T extends boolean = true> {
  slug?: T;
  isActive?: T;
  name?: T;
  service?:
    | T
    | {
        headertitle?: T;
        headerdetail?: T;
        headerimage?: T;
      };
  experiencelist?:
    | T
    | {
        titleexperience?: T;
        yearexperience?: T;
        id?: T;
      };
  content?:
    | T
    | {
        icontitle?: T;
        titleicon?: T;
        contentlist?:
          | T
          | {
              titlecontent?: T;
              detailcontent?: T;
              id?: T;
            };
      };
  servicecategorylist?:
    | T
    | {
        title?: T;
        detail?: T;
        imagelist?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  footer?:
    | T
    | {
        title?: T;
        detail?: T;
        image?: T;
        button?:
          | T
          | {
              title?: T;
              link?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-news-categories_select".
 */
export interface BlogNewsCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isActive?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-and-news_select".
 */
export interface BlogAndNewsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  publishedAt?: T;
  isActive?: T;
  category?: T;
  imagelist?:
    | T
    | {
        image?: T;
        id?: T;
      };
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo: number | Media;
  logonowhite: number | Media;
  navItems?:
    | {
        label: string;
        link?: string | null;
        hasDropdown?: boolean | null;
        navigationDescription: string;
        dropdownItems?:
          | {
              dropdownImage: number | Media;
              label: string;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaButtons?:
    | {
        /**
         * รูปภาพที่จะแสดงใน Button (ใส่หรือไม่ใส่ก็ได้)
         */
        iconbutton?: (number | null) | Media;
        label: string;
        link: string;
        variant?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * ใส่ keywords สำหรับ SEO (คั่นด้วยเครื่องหมายจุลภาค เช่น keyword1, keyword2)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  slides?:
    | {
        /**
         * Background image for this banner slide
         */
        image: number | Media;
        /**
         * Main headline text (e.g., "ABOUT GRASS")
         */
        mainTitle: string;
        /**
         * Sub-headline text in Thai
         */
        subTitle: string;
        /**
         * Descriptive text for this banner slide
         */
        description: string;
        imageIconButton?: (number | null) | Media;
        /**
         * Text for the call-to-action button
         */
        buttonText: string;
        /**
         * URL for the call-to-action button
         */
        buttonLink: string;
        /**
         * Optional overlay color to improve text readability
         */
        overlayColor?: ('dark' | 'light' | 'none') | null;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'published') | null;
  image: number | Media;
  gridlayout: {
    svg?: (number | null) | Media;
    Topic: string;
    services?: {
      serviceItems?:
        | {
            title: string;
            description?: string | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  HeaderOurServiceTop: string;
  HeaderOurServiceUnder: string;
  DescriptionOurService?: string | null;
  OurServiceItems?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload a video for the Golf Center section Background
   */
  videoBackground: number | Media;
  heading: string;
  description?: string | null;
  Button?:
    | {
        svg?: (number | null) | Media;
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  headerOurServiceProcess: string;
  descriptionOurServiceProcess?: string | null;
  processes?:
    | {
        imageIcon?: (number | null) | Media;
        backgroundImage?: (number | null) | Media;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  headerOurProductUpper: string;
  headerOurProductUnder?: string | null;
  ourProductItems?:
    | {
        title: string;
        description?: string | null;
        imageBackground?: (number | null) | Media;
        buttons?: {
          labelproduct?: string | null;
          linkproduct?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  headertestimonial: string;
  Secondarytestimonial: string;
  descriptiontestimonial?: string | null;
  testimonialItems?:
    | {
        title: string;
        thumbnail?: (number | null) | Media;
        video?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  logolistloop?:
    | {
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  csvIcon?: (number | null) | Media;
  headtext: string;
  text?: string | null;
  button?: {
    label?: string | null;
    link?: string | null;
  };
  imageBackground?: (number | null) | Media;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * ใส่ keywords สำหรับ SEO (คั่นด้วยเครื่องหมายจุลภาค เช่น keyword1, keyword2)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  page?:
    | {
        pagelabel?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  header: string;
  detail: string;
  imagelogo: number | Media;
  company: string;
  /**
   * วาง iframe code จาก Google Maps ที่นี่
   */
  mapIframe: string;
  social?:
    | {
        imageIcon: number | Media;
        socialname?: string | null;
        socialurl?: string | null;
        id?: string | null;
      }[]
    | null;
  contactlist?:
    | {
        imageIcon: number | Media;
        contactname?: string | null;
        contactdetaillist?:
          | {
              contactdetail?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contactbutton: {
    contactbuttonicon: number | Media;
    contactbutton?: string | null;
    contactbuttonlink?: string | null;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * ใส่ keywords สำหรับ SEO (คั่นด้วยเครื่องหมายจุลภาค เช่น keyword1, keyword2)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutus".
 */
export interface Aboutus {
  id: number;
  headerourstory: string;
  detailintro: string;
  image: number | Media;
  imagedetail: number | Media;
  detail: string;
  imagebackground: number | Media;
  experiencelist?:
    | {
        title: string;
        year: string;
        id?: string | null;
      }[]
    | null;
  imageourmission: number | Media;
  VISION: {
    headervision: string;
    detailvision: string;
  };
  ourmission: {
    header: string;
    detailourmissionlist?:
      | {
          detail: string;
          id?: string | null;
        }[]
      | null;
  };
  header: string;
  imageSlider?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  headerabove: string;
  headerbelow: string;
  historylist?:
    | {
        image: number | Media;
        title: string;
        detail: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * ใส่ keywords สำหรับ SEO (คั่นด้วยเครื่องหมายจุลภาค เช่น keyword1, keyword2)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ourproduct".
 */
export interface Ourproduct {
  id: number;
  heroSection?: {
    heading?: string | null;
    description?: string | null;
  };
  categorieSection?: {
    productCategories?:
      | {
          name?: string | null;
          slug?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * ใส่ keywords สำหรับ SEO (คั่นด้วยเครื่องหมายจุลภาค เช่น keyword1, keyword2)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "golf-center".
 */
export interface GolfCenter {
  id: number;
  titleheader?: string | null;
  description?: string | null;
  button?: {
    button?: string | null;
    buttonlink?: string | null;
  };
  /**
   * Upload a video for the Golf Center Background
   */
  videobackground: number | Media;
  textbelow?: string | null;
  mainfacilities?: {
    titleheader?: string | null;
    titlesecond?: string | null;
    imagefacility?: (number | null) | Media;
    facilities?:
      | {
          title?: string | null;
          detail?:
            | {
                title?: string | null;
                detail?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  chooseyourplan?: {
    whychooseus?: {
      titleheader?: string | null;
      titlesecond?: string | null;
      button?: string | null;
      buttonlink?: string | null;
      plan?:
        | {
            titleplan?: string | null;
            thumbnail?: (number | null) | Media;
            video?: (number | null) | Media;
            plandetail?:
              | {
                  /**
                   * ใส่ชื่อของหัวข้อรายละเอียดของแผน เช่น งบประมาณ
                   */
                  titledetail?: string | null;
                  /**
                   * ใส่จำนวนของรายละเอียดของแผน เช่น 2.5-3
                   */
                  numberdetail?: string | null;
                  /**
                   * ใส่รายละเอียดเพิ่มเติมของแผน เช่น ล้านบาท
                   */
                  moredetail?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * ใส่ keywords สำหรับ SEO (คั่นด้วยเครื่องหมายจุลภาค เช่น keyword1, keyword2)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-our-news".
 */
export interface BlogOurNew {
  id: number;
  heroSection?: {
    heading?: string | null;
    description?: string | null;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
    /**
     * ใส่ keywords สำหรับ SEO (คั่นด้วยเครื่องหมายจุลภาค เช่น keyword1, keyword2)
     */
    keywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  ga4?: string | null;
  gtm?: string | null;
  googleSearchConsole?: string | null;
  facebookPixel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  logonowhite?: T;
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        hasDropdown?: T;
        navigationDescription?: T;
        dropdownItems?:
          | T
          | {
              dropdownImage?: T;
              label?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  ctaButtons?:
    | T
    | {
        iconbutton?: T;
        label?: T;
        link?: T;
        variant?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        image?: T;
        mainTitle?: T;
        subTitle?: T;
        description?: T;
        imageIconButton?: T;
        buttonText?: T;
        buttonLink?: T;
        overlayColor?: T;
        id?: T;
      };
  status?: T;
  image?: T;
  gridlayout?:
    | T
    | {
        svg?: T;
        Topic?: T;
        services?:
          | T
          | {
              serviceItems?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
            };
      };
  HeaderOurServiceTop?: T;
  HeaderOurServiceUnder?: T;
  DescriptionOurService?: T;
  OurServiceItems?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  videoBackground?: T;
  heading?: T;
  description?: T;
  Button?:
    | T
    | {
        svg?: T;
        label?: T;
        link?: T;
        id?: T;
      };
  headerOurServiceProcess?: T;
  descriptionOurServiceProcess?: T;
  processes?:
    | T
    | {
        imageIcon?: T;
        backgroundImage?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  headerOurProductUpper?: T;
  headerOurProductUnder?: T;
  ourProductItems?:
    | T
    | {
        title?: T;
        description?: T;
        imageBackground?: T;
        buttons?:
          | T
          | {
              labelproduct?: T;
              linkproduct?: T;
            };
        id?: T;
      };
  headertestimonial?: T;
  Secondarytestimonial?: T;
  descriptiontestimonial?: T;
  testimonialItems?:
    | T
    | {
        title?: T;
        thumbnail?: T;
        video?: T;
        id?: T;
      };
  logolistloop?:
    | T
    | {
        logo?: T;
        id?: T;
      };
  csvIcon?: T;
  headtext?: T;
  text?: T;
  button?:
    | T
    | {
        label?: T;
        link?: T;
      };
  imageBackground?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  page?:
    | T
    | {
        pagelabel?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  header?: T;
  detail?: T;
  imagelogo?: T;
  company?: T;
  mapIframe?: T;
  social?:
    | T
    | {
        imageIcon?: T;
        socialname?: T;
        socialurl?: T;
        id?: T;
      };
  contactlist?:
    | T
    | {
        imageIcon?: T;
        contactname?: T;
        contactdetaillist?:
          | T
          | {
              contactdetail?: T;
              id?: T;
            };
        id?: T;
      };
  contactbutton?:
    | T
    | {
        contactbuttonicon?: T;
        contactbutton?: T;
        contactbuttonlink?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutus_select".
 */
export interface AboutusSelect<T extends boolean = true> {
  headerourstory?: T;
  detailintro?: T;
  image?: T;
  imagedetail?: T;
  detail?: T;
  imagebackground?: T;
  experiencelist?:
    | T
    | {
        title?: T;
        year?: T;
        id?: T;
      };
  imageourmission?: T;
  VISION?:
    | T
    | {
        headervision?: T;
        detailvision?: T;
      };
  ourmission?:
    | T
    | {
        header?: T;
        detailourmissionlist?:
          | T
          | {
              detail?: T;
              id?: T;
            };
      };
  header?: T;
  imageSlider?:
    | T
    | {
        image?: T;
        id?: T;
      };
  headerabove?: T;
  headerbelow?: T;
  historylist?:
    | T
    | {
        image?: T;
        title?: T;
        detail?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ourproduct_select".
 */
export interface OurproductSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  categorieSection?:
    | T
    | {
        productCategories?:
          | T
          | {
              name?: T;
              slug?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "golf-center_select".
 */
export interface GolfCenterSelect<T extends boolean = true> {
  titleheader?: T;
  description?: T;
  button?:
    | T
    | {
        button?: T;
        buttonlink?: T;
      };
  videobackground?: T;
  textbelow?: T;
  mainfacilities?:
    | T
    | {
        titleheader?: T;
        titlesecond?: T;
        imagefacility?: T;
        facilities?:
          | T
          | {
              title?: T;
              detail?:
                | T
                | {
                    title?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  chooseyourplan?:
    | T
    | {
        whychooseus?:
          | T
          | {
              titleheader?: T;
              titlesecond?: T;
              button?: T;
              buttonlink?: T;
              plan?:
                | T
                | {
                    titleplan?: T;
                    thumbnail?: T;
                    video?: T;
                    plandetail?:
                      | T
                      | {
                          titledetail?: T;
                          numberdetail?: T;
                          moredetail?: T;
                          id?: T;
                        };
                    id?: T;
                  };
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-our-news_select".
 */
export interface BlogOurNewsSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  ga4?: T;
  gtm?: T;
  googleSearchConsole?: T;
  facebookPixel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null)
      | ({
          relationTo: 'blog-and-news';
          value: number | BlogAndNew;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}